export default {
    banner:[],
    showLoading:false,
    bSearch:false,
    bDrawer:false,
    bHomeAudio:false,
    bList:false,
    AudioList:[],
    nowAudio:{},
    AudioPlay:false,
    AudioPercent:0,
    PlayList:[],
    SongList:[],
    SongInfo:{},
    viewAudio:false,
    isHome:true,
}